#!/bin/bash
# Quick deploy commands - copy/paste into terminals

echo "=========================================="
echo "mPanel Billing Core - Deploy Commands"
echo "=========================================="
echo ""
echo "FROM YOUR LOCAL MACHINE:"
echo "------------------------"
echo ""
echo "# 1. Upload files to mpanel-core"
echo "cd /home/bonex/MigraWeb/MigraHosting/dev/migra-panel"
echo "scp migrations/20251127_billing_core.sql mhadmin@10.1.10.206:/tmp/"
echo "scp src/routes/ordersPublic.js mhadmin@10.1.10.206:/tmp/"
echo "scp src/routes/adminCustomers.js mhadmin@10.1.10.206:/tmp/"
echo "scp src/routes/adminSubscriptions.js mhadmin@10.1.10.206:/tmp/"
echo "scp src/routes/adminServers.js mhadmin@10.1.10.206:/tmp/"
echo "scp src/server.js mhadmin@10.1.10.206:/tmp/"
echo "scp deploy-billing-core.sh mhadmin@10.1.10.206:/tmp/"
echo ""
echo "# 2. Rebuild frontend"
echo "cd frontend && npm run build"
echo "tar czf ../frontend-dist.tar.gz dist/"
echo "scp ../frontend-dist.tar.gz mhadmin@10.1.10.206:/tmp/"
echo ""
echo "=========================================="
echo "ON mpanel-core (10.1.10.206) AS ROOT:"
echo "=========================================="
echo ""
echo "# Move files to /opt/mpanel"
echo "cd /opt/mpanel"
echo "mv /tmp/20251127_billing_core.sql migrations/"
echo "mv /tmp/ordersPublic.js src/routes/"
echo "mv /tmp/adminCustomers.js src/routes/"
echo "mv /tmp/adminSubscriptions.js src/routes/"
echo "mv /tmp/adminServers.js src/routes/"
echo "mv /tmp/server.js src/"
echo "mv /tmp/deploy-billing-core.sh ."
echo "chmod +x deploy-billing-core.sh"
echo ""
echo "# Deploy frontend"
echo "cd /tmp"
echo "tar xzf frontend-dist.tar.gz"
echo "rm -rf /var/www/migrapanel.com/public/*"
echo "cp -r dist/* /var/www/migrapanel.com/public/"
echo "chown -R www-data:www-data /var/www/migrapanel.com/public"
echo ""
echo "# Run deployment"
echo "cd /opt/mpanel"
echo "./deploy-billing-core.sh"
echo ""
echo "=========================================="
echo "VERIFICATION:"
echo "=========================================="
echo ""
echo "# Test APIs"
echo "curl http://localhost:2271/api/admin/customers | jq"
echo "curl http://localhost:2271/api/admin/subscriptions/tasks | jq"
echo "curl http://localhost:2271/api/admin/servers | jq"
echo ""
echo "# Check frontend"
echo "curl -I http://migrapanel.com"
echo "curl -I http://migrapanel.com/admin/customers"
echo ""
echo "# Check backend logs"
echo "pm2 logs tenant-billing --lines 50"
echo ""
echo "=========================================="
echo "DONE!"
echo "=========================================="
echo ""
echo "Next: Visit http://migrapanel.com and check /admin/customers"
