-- Migration: Create AI builder tables
-- Created: 2024-01-10

-- Create ai_builder_projects table
CREATE TABLE IF NOT EXISTS ai_builder_projects (
  id SERIAL PRIMARY KEY,
  website_id INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  business_type VARCHAR(100) NOT NULL,
  business_name VARCHAR(200) NOT NULL,
  business_description TEXT,
  template VARCHAR(50) NOT NULL,  -- 'business', 'ecommerce', 'portfolio', 'blog', 'landing', 'restaurant'
  color_scheme VARCHAR(50),
  features JSONB DEFAULT '[]',
  language VARCHAR(10) DEFAULT 'en',
  status VARCHAR(50) NOT NULL DEFAULT 'pending',  -- 'pending', 'generating', 'completed', 'failed'
  generated_css TEXT,
  error_message TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  generated_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create ai_generated_pages table
CREATE TABLE IF NOT EXISTS ai_generated_pages (
  id SERIAL PRIMARY KEY,
  project_id INTEGER NOT NULL REFERENCES ai_builder_projects(id) ON DELETE CASCADE,
  page_name VARCHAR(100) NOT NULL,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  meta JSONB DEFAULT '{}',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  
  UNIQUE (project_id, page_name)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_ai_builder_projects_website_id ON ai_builder_projects(website_id);
CREATE INDEX IF NOT EXISTS idx_ai_builder_projects_status ON ai_builder_projects(status);
CREATE INDEX IF NOT EXISTS idx_ai_builder_projects_template ON ai_builder_projects(template);
CREATE INDEX IF NOT EXISTS idx_ai_generated_pages_project_id ON ai_generated_pages(project_id);

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_ai_builder_projects_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ai_builder_projects_updated_at
  BEFORE UPDATE ON ai_builder_projects
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_builder_projects_updated_at();

-- Add comments
COMMENT ON TABLE ai_builder_projects IS 'AI website builder projects';
COMMENT ON COLUMN ai_builder_projects.business_type IS 'Type of business for AI content generation';
COMMENT ON COLUMN ai_builder_projects.business_name IS 'Business name for branding';
COMMENT ON COLUMN ai_builder_projects.business_description IS 'Business description for AI context';
COMMENT ON COLUMN ai_builder_projects.template IS 'Selected template: business, ecommerce, portfolio, blog, landing, restaurant';
COMMENT ON COLUMN ai_builder_projects.color_scheme IS 'Selected color scheme';
COMMENT ON COLUMN ai_builder_projects.features IS 'Additional features to include';
COMMENT ON COLUMN ai_builder_projects.status IS 'Project status: pending, generating, completed, failed';
COMMENT ON COLUMN ai_builder_projects.generated_css IS 'Generated CSS for the website';

COMMENT ON TABLE ai_generated_pages IS 'Pages generated by AI website builder';
COMMENT ON COLUMN ai_generated_pages.page_name IS 'Page identifier (home, about, services, etc.)';
COMMENT ON COLUMN ai_generated_pages.title IS 'Page title';
COMMENT ON COLUMN ai_generated_pages.content IS 'Generated HTML content';
COMMENT ON COLUMN ai_generated_pages.meta IS 'SEO meta information (description, keywords)';
